import SwiftUI
import Supabase

struct TrainerSession: Decodable, Identifiable {
    let id: UUID
    let trainer: UUID
    let user_id: UUID
    let user_email: String?
    let title: String?
    let start_at: Date
    let end_at: Date?
    let meet_url: String?
    let created_at: Date?
}

struct CustomExerciseRow: Decodable, Identifiable {
    let id: UUID
    let trainer: UUID
    let name: String
    let category: String?
    let equipment: String?
    let primary_muscles: String?
    let secondary_muscles: String?
    let instructions: String?
    let images: String?
    let created_at: Date?
    let updated_at: Date?
}

struct TierRow: Decodable, Identifiable {
    let id: UUID
    let trainer: UUID
    let price: Int?
    let key: String?
    let name: String
    let active: Bool?
    let stripe_price_id: String?
}

struct CoachRoutinesView: View {
    var body: some View {
        standardScaffold(title: "Custom Routines") {
            Text("Browse and manage routines assigned to you. In a future update, we can let you request changes or favorite routines here.")
                .font(Theme.Fonts.Body3)
                .foregroundStyle(Theme.Colors.NeutralLight1)
        }
    }
}

struct CoachAIInsightsView: View {
    var body: some View {
        standardScaffold(title: "AI Insights") {
            Text("Insights about your progress generated by AI. Coming soon: weekly summaries and recommendations.")
                .font(Theme.Fonts.Body3)
                .foregroundStyle(Theme.Colors.NeutralLight1)
        }
    }
}

struct CoachExercisesView: View {
    @AppStorage("TRAINER_ID_KEY") private var trainerId: String = ""
    @State private var exercises: [CustomExerciseRow] = []
    @State private var loading = true
    @State private var error: String? = nil

    var body: some View {
        standardScaffold(title: "Custom Exercises") {
            if loading {
                ProgressView().tint(Theme.Colors.Primary1)
            } else if let error = error {
                Text(error).foregroundStyle(.red)
            } else if exercises.isEmpty {
                Text("No custom exercises yet.")
                    .font(Theme.Fonts.Body3)
                    .foregroundStyle(Theme.Colors.NeutralLight1)
            } else {
                List(exercises) { ex in
                    VStack(alignment: .leading, spacing: 4) {
                        Text(ex.name)
                            .font(Theme.Fonts.SubHeading5)
                            .foregroundStyle(Theme.Colors.NeutralLight1)
                            .lineLimit(1).minimumScaleFactor(0.8)
                        HStack(spacing: 8) {
                            if let cat = ex.category { pill(cat) }
                            if let eq = ex.equipment { pill(eq) }
                        }
                        if let instr = ex.instructions, !instr.isEmpty {
                            Text(instr)
                                .font(Theme.Fonts.Body6)
                                .foregroundStyle(Theme.Colors.NeutralLight1.opacity(0.9))
                                .lineLimit(3)
                                .minimumScaleFactor(0.8)
                        }
                    }
                    .listRowBackground(Theme.Colors.NeutralDark)
                }
                .scrollContentBackground(.hidden)
                .background(Theme.Colors.NeutralDark)
            }
        }
        .task { await fetchExercises() }
    }

    private func fetchExercises() async {
        loading = true; error = nil
        do {
            guard let trainerUUID = UUID(uuidString: trainerId) else { loading = false; return }
            let resp = try await supabase
                .from("exercises_custom")
                .select("*")
                .eq("trainer", value: trainerUUID)
                .order("created_at", ascending: false)
                .execute()
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .flexible(["yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX","yyyy-MM-dd'T'HH:mm:ssXXXXX","yyyy-MM-dd HH:mm:ss","yyyy-MM-dd"])    
            exercises = try decoder.decode([CustomExerciseRow].self, from: resp.data)
            loading = false
        } catch {
            self.error = error.localizedDescription
            loading = false
        }
    }

    private func pill(_ text: String) -> some View {
        Text(text)
            .font(Theme.Fonts.Body7)
            .padding(.horizontal, 8).padding(.vertical, 4)
            .background(.ultraThinMaterial)
            .clipShape(Capsule())
    }
}

struct CoachSessionsView: View {
    @State private var sessions: [TrainerSession] = []
    @State private var loading = true
    @State private var error: String? = nil

    var body: some View {
        standardScaffold(title: "1-on-1 Sessions") {
            if loading {
                ProgressView().tint(Theme.Colors.Primary1)
            } else if let error = error {
                Text(error)
                    .font(Theme.Fonts.Body3)
                    .foregroundStyle(.red)
            } else if sessions.isEmpty {
                Text("No upcoming sessions.")
                    .font(Theme.Fonts.Body3)
                    .foregroundStyle(Theme.Colors.NeutralLight1)
            } else {
                List {
                    ForEach(sessions) { s in
                        VStack(alignment: .leading, spacing: 6) {
                            Text(s.title ?? "Session")
                                .font(Theme.Fonts.SubHeading5)
                                .foregroundStyle(Theme.Colors.NeutralLight1)
                                .lineLimit(1).minimumScaleFactor(0.8)
                            Text(dateRange(start: s.start_at, end: s.end_at))
                                .font(Theme.Fonts.Body5)
                                .foregroundStyle(Theme.Colors.NeutralLight1.opacity(0.8))
                            if let urlStr = s.meet_url, let url = URL(string: urlStr) {
                                Link(destination: url) {
                                    Label("Join meeting", systemImage: "video.fill")
                                        .font(Theme.Fonts.Body6)
                                }
                                .tint(Theme.Colors.Primary1)
                            }
                        }
                        .listRowBackground(Theme.Colors.NeutralDark)
                    }
                }
                .scrollContentBackground(.hidden)
                .background(Theme.Colors.NeutralDark)
            }
        }
        .task { await fetchSessions() }
    }

    private func fetchSessions() async {
        loading = true; error = nil
        do {
            guard let userId = supabase.auth.currentUser?.id else { loading = false; return }
            let resp = try await supabase
                .from("trainer_sessions")
                .select("*")
                .eq("user_id", value: userId)
                .order("start_at")
                .execute()
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .flexible([
                "yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX",
                "yyyy-MM-dd'T'HH:mm:ssXXXXX",
                "yyyy-MM-dd HH:mm:ss",
                "yyyy-MM-dd"
            ])
            sessions = try decoder.decode([TrainerSession].self, from: resp.data)
            loading = false
        } catch {
            self.error = error.localizedDescription
            loading = false
        }
    }

    private func dateRange(start: Date, end: Date?) -> String {
        let df = DateFormatter()
        df.dateStyle = .medium
        df.timeStyle = .short
        if let end = end { return "\(df.string(from: start)) – \(df.string(from: end))" }
        return df.string(from: start)
    }
}

struct CoachPrivateContentView: View {
    var body: some View {
        standardScaffold(title: "Private Content") {
            Text("Access members-only videos, files, or links from your coach.")
                .font(Theme.Fonts.Body3)
                .foregroundStyle(Theme.Colors.NeutralLight1)
        }
    }
}

struct CoachBlogView: View {
    var body: some View {
        standardScaffold(title: "Blog Updates") {
            Text("Read your coach's latest updates and posts.")
                .font(Theme.Fonts.Body3)
                .foregroundStyle(Theme.Colors.NeutralLight1)
        }
    }
}

struct CoachTiersView: View {
    @AppStorage("TRAINER_ID_KEY") private var trainerId: String = ""
    @State private var tiers: [TierRow] = []
    @State private var loading = true
    @State private var error: String? = nil

    var body: some View {
        standardScaffold(title: "Membership Tiers") {
            if loading { ProgressView().tint(Theme.Colors.Primary1) }
            else if let error = error { Text(error).foregroundStyle(.red) }
            else if tiers.isEmpty {
                Text("No tiers available.")
                    .font(Theme.Fonts.Body3)
                    .foregroundStyle(Theme.Colors.NeutralLight1)
            } else {
                VStack(spacing: 12) {
                    ForEach(tiers) { t in
                        ZStack {
                            RoundedRectangle(cornerRadius: 16, style: .continuous)
                                .fill(.thinMaterial)
                                .overlay(RoundedRectangle(cornerRadius: 16).stroke(Theme.Colors.Primary1.opacity(0.12), lineWidth: 1))
                            HStack {
                                VStack(alignment: .leading, spacing: 4) {
                                    Text(t.name)
                                        .font(Theme.Fonts.SubHeading5)
                                        .foregroundStyle(Theme.Colors.NeutralLight1)
                                        .lineLimit(1).minimumScaleFactor(0.8)
                                    HStack(spacing: 8) {
                                        if let price = t.price { pill("$\(price)/mo") }
                                        if let key = t.key { pill(key) }
                                        if let active = t.active { pill(active ? "Active" : "Inactive") }
                                    }
                                }
                                Spacer()
                                Button {
                                    // Hook to purchase / manage subscription here
                                } label: {
                                    Text("Manage")
                                        .font(Theme.Fonts.Body6)
                                        .padding(.horizontal, 12).padding(.vertical, 8)
                                        .background(Theme.Colors.Primary1)
                                        .foregroundStyle(Theme.Colors.NeutralDark)
                                        .clipShape(Capsule())
                                }
                            }
                            .padding(14)
                        }
                    }
                }
                .padding(.horizontal)
            }
        }
        .task { await fetchTiers() }
    }

    private func fetchTiers() async {
        loading = true; error = nil
        do {
            guard let trainerUUID = UUID(uuidString: trainerId) else { loading = false; return }
            let resp = try await supabase
                .from("tiers")
                .select("*")
                .eq("trainer", value: trainerUUID)
                .order("price")
                .execute()
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .flexible(["yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX","yyyy-MM-dd'T'HH:mm:ssXXXXX","yyyy-MM-dd HH:mm:ss","yyyy-MM-dd"])    
            tiers = try decoder.decode([TierRow].self, from: resp.data)
            loading = false
        } catch {
            self.error = error.localizedDescription
            loading = false
        }
    }

    private func pill(_ text: String) -> some View {
        Text(text)
            .font(Theme.Fonts.Body7)
            .padding(.horizontal, 8).padding(.vertical, 4)
            .background(.ultraThinMaterial)
            .clipShape(Capsule())
    }
}

struct CoachVideosView: View {
    let videos: [String]
    var body: some View {
        standardScaffold(title: "Videos") {
            if videos.isEmpty {
                Text("No videos from your coach yet.")
                    .font(Theme.Fonts.Body3)
                    .foregroundStyle(Theme.Colors.NeutralLight1)
            } else {
                ScrollView {
                    VStack(spacing: 12) {
                        ForEach(videos, id: \.self) { link in
                            if let id = extractYouTubeID(from: link) {
                                ZStack {
                                    RoundedRectangle(cornerRadius: 16, style: .continuous)
                                        .fill(.ultraThinMaterial)
                                        .shadow(radius: 8, y: 4)
                                    YouTubeView(videoID: id)
                                        .frame(height: 200)
                                        .cornerRadius(16)
                                }
                            }
                        }
                    }
                    .padding(.horizontal)
                }
            }
        }
    }
}

// MARK: - Shared scaffold
private func standardScaffold<Content: View>(title: String, @ViewBuilder content: () -> Content) -> some View {
    VStack(alignment: .leading, spacing: 16) {
        HStack {
            Text(title)
                .font(Theme.Fonts.Heading4)
                .foregroundStyle(Theme.Colors.Primary1)
                .lineLimit(1).minimumScaleFactor(0.7)
            Spacer()
        }
        .padding(.horizontal)
        content()
        Spacer(minLength: 0)
    }
    .padding()
    .frame(maxWidth: .infinity, maxHeight: .infinity)
    .background(Theme.Colors.NeutralDark)
}

#Preview {
    NavigationStack { CoachRoutinesView() }
}
